
spring:
  redis:
    host: 10.10.2.217
    # ??????6379
    port: 32426
    password: Parav1ew
    # ??????
    database: 0
    timeout: 5000
    jedis:
      pool:
        # ???????????
        min-idle: 5
        # ???????????
        max-idle: 10
        # ????????????
        max-active: 20
        # #???????????????????????
        max-wait: 2000
        testOnCreate: true
        testOnBorrow: true
        testOnReturn: true
        testWhileIdle: true
    lettuce:
      cluster:
        refresh:
          adaptive: true
        period: 60000
      pool:
        # ???????????
        min-idle: 5
        # ???????????
        max-idle: 10
        # ????????????
        max-active: 20
        # #???????????????????????
        max-wait: 2000
        testOnCreate: true
        testOnBorrow: true
        testOnReturn: true
        testWhileIdle: true

bloom:
  enable: true
  missRate: 0.03
  size: 10
  expireTime: 60000
  reset: 180